### ISSUE TITLE
Covers thumbnails for browsing don't show

### ISSUE THREAD

**Issue by beville** [ajslater/codex#132]
I just gave a try to codex 0.9.9 (installed via pip on Ubuntu 20.04, python3.9)

I pointed it at a folder with about 40 cbz files, all of them already tagged with comicinfo.xml.  The files seemed to be scanned in perfectly.  I can browse by series, issues, publisher, folder.  I can view metadata for each comic.  And finally I can read each comic just fine, start to finish

The only thing that _doesn't_ seem to be working is the cover thumbnail display while browsing. Instead of cover thumbnails, there are only the swirly circle gifs.  There doesn't seem to be anything of interest in the logs.

Any idea of how I can troubleshoot this?

**Comment by ajslater** [comment]
First i would go into the admin panel and go to "Queue Jobs".
Select Recreate All Comic Covers and queue the job
With 40 comics you should see covers appear quite rapidly.

Should that fail, I'd look at codex's logs and see if anything looks odd there. You may be able to see it running the cover generator. To get more detailed logs, run codex with the `LOGLEVEL=VERBOSE` environment variable

**Comment by beville** [comment]
Ah, I did that, and in the browser (Firefox) all the covers appeared!  And then I refreshed and the all went back to the swirls!  So I tried again in a different browser and every just looked great. So, it must be something about my Firefox setup. Maybe a plugin or setting is being too aggressive about privacy or something.

(I should have tried this before posting an issue, but I ran into the same problem when I tried codex a few months ago, and I had same issue across multiple devices and browser.  Maybe something has been fixed since then.)

Thanks for the swift help!  I'll dig into this later, see if I can't figure out the exact issue with my Firefox and Codex.

**Comment by beville** [comment]
OK, I went through the process again, and I saw that for some reasons the cover scan didn't actually occur when I added the library.  Happened again with a much larger library.  After all the metadata scanning completed, I ran "Create Missing Comic Covers" and they all got read in fine.

Attaching a portion of the verbose log where I just deleted the smaller library, and then re-added it.  Same problem and at 10:47:47 I see

```
2022-04-02 10:47:46 PDT VERBOSE  Imported 44 comics at 11 comics per second..
2022-04-02 10:47:47 PDT INFO     Created covers for 0/44 comics.
```

About two minutes later (10:49:20), I ran the  "Create Missing Comic Covers" job and they got added in.

**Comment by ajslater** [comment]
I'm not able to replicate this behavior.

I see some DEBUG level logging statements in the code. If you could run
Codex with the environment variable LOGLEVEL=DEBUG, the logs might give me
further clues as to why this might be happening.

Thanks for reporting this.

**Comment by beville** [comment]
OK, used DEBUG this time.  Started from scratch with no config folder.  Added a library folder with just comics in it.  No thumbnails displayed until the  "Create Missing Comic Covers" job at 12:56:42

[codex.log](https://github.com/ajslater/codex/files/8403291/codex.log)

Also not in this log, but after I add a new comic file to the existing folder, I see the same issue. Comic is added, but nothing is displayed.  It's interesting, because the debug log even indicates that the new cover thumbnail was created at initial scan time...

Anyways, this is not a blocker for me in any way, so certainly no urgency from me to address this.

**Comment by ajslater** [comment]
This is feeling a bit like a browser caching issue. I should figure out how to nuke the browser cache for missing comic covers better. I don't think what I'm doing is working all the time.

**Comment by beville** [comment]
0.9.11 fixes this.

Thanks!
