### ISSUE TITLE
Issue number not getting pulled from filename if no metadata/tags

### ISSUE THREAD

**Issue by beville** [ajslater/codex#139]
I notice that when Codex scans a folder and a few comics that don't (yet) have tags, but are cleanly named, it can't figure out the issue number.

For example:

`The Walking Dead #002 (2003).cbz`
`The Walking Dead #3.cbz`
`The Walking Dead 4.cbz`

are imported the correct series, but all as issue 0.

**Comment by ajslater** [comment]
Codex does attempt to pull issue number from filename, but isn't always successful as there is enormous variation in file naming. However, the examples you provided look like patterns codex _should_ be able to derive the issue number from so ill be looking into this. Thanks!

**Comment by ajslater** [comment]
These patterns should be fixed in codex v0.9.13 #143
