### ISSUE TITLE
CSRF fails on library action

### ISSUE THREAD

**Issue by Dracon23** [ajslater/codex#142]
Triggering any Action on a library in the admin interface will raise a 403 Forbidden by Django, caused by CSRF failure.

Running via
Docker: ajslater/codex:latest
Host: RasPi4b, 8GB using Manjaro ARM

[Compose](https://dpaste.org/dBAim)

**Comment by ajslater** [comment]
I'm not able to replicate this.
Could you try performing an admin action with another browser. I suspect that your primary browser may be blocking cookies or javascript bits that set the CSRF token.

**Comment by ajslater** [comment]
Closed as unreproducible
