### ISSUE TITLE
Fractional issue numbers are rounded down for display in folder view

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#144]
I have some comics that have fractional issue numbers, e.g. there might be an issue 6.5 between issues 6 and 7 (typically, this is used for e.g. short comics the author publishes online between main issues, but there's a lot of variation). These appear to be sorted properly when using "order by name", but the issue number is truncated, e.g. _Always Human_ 1.5 is displayed as "Always Human #001 - Fanart Feature 2".

When using other display modes, e.g. view by series, it shows up as "#001½".

**Comment by ajslater** [comment]
Thanks for reporting this. This was a weird judgement call by me. I do store issue numbers in the database as decimals, but I always thought that actual decimal issue numbers were so rare as to only include half issues.
What your case means is that I will probably just delete the display filter that translates the decimal into fraction characters and display normal decimals.

**Comment by ToxicFrog** [comment]
Yeah, in addition to half-issues I have a lot of fraction-of-ten issues like .1, .2, and .6, and at least one series that has issues 8, 8.50, 8.51, 8.52, 8.53, and 8.54.

**Comment by beville** [comment]
Marvel is pretty bad with these weird issue number suffixes. 

To complicate things even more are issues like these:

[_Earth X #½_](https://comicvine.gamespot.com/earth-x-1-2/4000-203972)
[_Avengers #001½_](https://comicvine.gamespot.com/avengers-11-2-the-death-trap-of-doctor-doom/4000-78495/)

And these:

[_The Amazing Spider-Man #78.BEY_](https://comicvine.gamespot.com/the-amazing-spider-man-78bey/4000-894132/)
[_The Amazing Spider-Man #53.LR_](https://comicvine.gamespot.com/the-amazing-spider-man-53lr-fallen-order-part-four/4000-819481/)

And even these with no decimal point:

[_Wolverine & the X-Men #27AU_](http://www.comicvine.com/wolverine-and-the-x-men-27au-age-of-ultron-road-tr/4000-397554/)
[_Fantastic Four #5AU_](http://www.comicvine.com/fantastic-four-5au-the-death-of-the-family-richard/4000-395247/)

One approach is to store the issues as both floats and as original strings, and use the numeric column for sorting queries, and the string column for presentation.

**Comment by ajslater** [comment]
I hadn't heard of those alphanumeric suffixes until recently.

Similar to your suggestion I might make the sort column a zero padded string, so the alpha suffix can be included in the sort.

**Comment by ajslater** [comment]
Codex v0.9.14 replaces ½ glyphs in issues with decimals and should display decimal issues to two places.

I'm leaving this issue open as a 🔜 version of codex will change the the type of the issue in the database to a string to support the examples given by beville.

**Comment by ajslater** [comment]
Codev v0.10.1 supports alphanumeric issues and handles alphanumeric issue suffixes fairly well.

Reopen if issues persist.
