### ISSUE TITLE
Option to display filenames instead of inferred metadata

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#145]
Most of my comics have no metadata, and while any given folder is named consistently and usefully there is not necessarily any consistency _across_ folders, so metadata inference from filenames isn't really workable and in a lot of cases it will do things like infer the issue or volume title as the series title, fail to detect the issue number, etc.

That's fine, because the filenames are all correct, except that there doesn't seem to be any option to _display_ the filenames, so I will end up with, for example, an entire folder of comics labeled `Book #000` with no way of differentiating them except the cover art.

I don't think it's reasonable to expect Codex to infer useful metadata given my lack of a consistent naming scheme, but it would be nice if I could tell it not to try and just display the filename as is.

**Comment by ajslater** [comment]
Codex v0.9.14 now supports this.
