### ISSUE TITLE
Mark Read doesn't recurse into subdirectories

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#152]
Consider the following folder structure:
```
Narbonic/
  Extras/
    [a bunch of CBZs]
  Fan Content/
    [more CBZs]
  Narbonic Volume 1.cbz
  Narbonic Volume 2.cbz
```

If you use the threedots menu to "mark entire folder read" on `Narbonic`, none of the stuff in `Extras` or `Fan Content` will be affected (nor the folders themselves). This also means that `Narbonic` will now show up as "partially read", which means you never get a "mark entire folder unread" option, and if you want that you have to go into it and mark the CBZs as unread individually.

**Comment by ajslater** [comment]
Fixed in v0.10.1
