### ISSUE TITLE
Folder-level read/unread status determination ignores folder contents you haven't interacted with

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#153]
E.g. if you import a folder with ten issues, and mark the first one read, and don't do anything with the rest, the folder is now considered "read", because it's not considering the status of the other nine issues. Once you start reading the second issue the containing folder becomes "partially read", and when you finish the issue it is "unread" again (until you open issue 3). In general, it seems like comics don't exist to the read/unread marker until you either manually twiddle their read status, or open them for reading at least once.

For directories that only contain files and not subdirectories, you can work around this by marking the whole thing read, then marking it unread again; this will toggle the read status on every file in the directory on and then off and make them visible to the read marker. This is not viable on more complicated directory structures due to #152.

Codex is otherwise fully aware of the directory contents, e.g. the number-of-children bubble in the top left of the directory tile is correct.

**Comment by ajslater** [comment]
Fixed in v0.10.1
