### ISSUE TITLE
Text on the Mark Read/Unread menu doesn't update when used

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#154]
Tap the threedots menu, select "mark issue read".
Now tap it again...and the menu entry still says "mark issue read". (Selecting it will mark the issue unread, since the actual semantics of that menu option are "toggle read marker".) Refresh the page and it's fixed.
It looks like the menu text is generated on page load and not updated thereafter, even if the read status of the file or directory in question changes.

**Comment by ajslater** [comment]
Fixed in v0.10.1
