### ISSUE TITLE
Interaction between directories, progress bars, and Mark Read is counterintuitive

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#157]
Specifically, what seems to happening here is:
- "mark read" and "mark unread" don't move the progress bar on individual issues, only toggle the `is-read` flag
- directory-level progress bars are derived from the progress bars of their contents, completely ignoring read status

This results in some confusing behaviour, of which the most obvious is probably this: if I have a directory containing (say) 10 issues, and I mark five of them read (because I read them outside of codex), and then read issue 6, the directory shows up as "partially read, 10% done"; by the time I'm done issue 10, the directory is "fully read, 50% done".

Similarly, if I "mark entire folder read", it is now "fully read, 0% done".

At the same time, you don't want to blindly move the page cursor around when fiddling with the read flag, because if someone is halfway through a book you don't want to lose their place because they did some bulk editing action.

My first draft at how to deal with this would be something like:
- when marking a file read, set the page cursor to the end of the file iff it is currently at the start
- when marking a file unread, set the page cursor to the start of the file iff it is currently at the end

and/or:
- when generating the progress bar for a directory, count files that are marked read as having the page cursor at the end no matter where it actually is

Either one of these would be sufficient to make directory-level progress bars sync up with the read status of the contents. Only implementing the first means that the directory progress bar goes backwards when you start rereading something you've already read, which may or may not be desireable -- personally I don't like it, but I think it could reasonably be argued either way. Only implementing the second means that when you "mark read" a book you've never opened, its file-level progress bar stays at 0%.

**Comment by ajslater** [comment]
Looking into it, solution two is what should be implemented, but i reckon it's broken.

**Comment by ajslater** [comment]
Fixed in v0.10.1
