### ISSUE TITLE
Useless scrollbar appears when shrink mode is set to "height"

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#166]
0.10.3 fixed an issue with the scrollbar always being visible whether the screen was scrollable or not. However -- at least in Chrome and Firefox on Linux -- when the shrink mode is set to "fit height", the image is exactly sized to the height of the screen, and the div *containing* the image ends up a few px larger, causing a scrollbar to appear.

Setting the image height to 99vh rather than 100vh fixes it, but at the cost of a visible black bar at the bottom of the screen. Disabling vertical scrolling entirely with `html { overflow-y: hidden; }` also fixes it, but to work properly needs to be done conditionally (only when shrink mode is "height" or "screen"), as this disables vertical scrolling completely, which may be a problem in shrink-to-width mode.

**Comment by ajslater** [comment]
I believe this is fixed with v0.10.5
