### ISSUE TITLE
OPDS-pse support

### ISSUE THREAD

**Issue by sunjam** [ajslater/codex#168]
:wave: OPDS-pse support for Codex :smiley: Thanks for considering.

Full details at https://github.com/anansi-project/opds-pse

The OPDS Page Streaming Extension (OPDS-PSE) is an unofficial extension of the [Open Distribution Publication System](https://specs.opds.io/opds-1.2). Its goal is to enrich the OPDS feed with information allowing the client to request a specific page of a document without having to download it completely.

This extension was designed primarily for comic books, to allow reading them on connected devices without having to wait for the book to be completely downloaded.

**Comment by ajslater** [comment]
Codex v0.12.0 supports OPDS v1.2, OPDS-PSE v1.1 and OpenSearch via OPDS.

I'd consider OPDS v2 someday, but i don't think there's much client support yet and I'm not feeling like a leader here.
