### ISSUE TITLE
Enforce cover image size

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#17]
Some cover images may be dual width pages, such as the attached example. Might be nice to have them forced/stretched to be uniform.

![image](https://user-images.githubusercontent.com/17379660/91627639-8167ec00-e96d-11ea-9afd-a7d150812a93.png)

**Comment by ajslater** [comment]
That would make individual browser tiles look nicer. But without much more space in between tiles, I think it would make the overall browser page look much worse or inconsistent. An early version of Codex (v0.3.0 ?) actually did have larger double width browser tiles and it was eventually abandoned. I might look into it again, but it won't be a priority.
