### ISSUE TITLE
Feature Request: Enhanced Touchscreen Device Support

### ISSUE THREAD

**Issue by beville** [ajslater/codex#172]
My ideal use case for Codex would be use it a "web app" on a tablet, where I save a shortcut on the home screen, and then launch a dedicated web browser instance with that.  For the the most part Codex work great for for the comic browsing mode, but there's a few bits missing from the reader mode that would enhance the experience:

1. Swipe left/right for page turns. (Minor thing, but quality-of-life enhancement)
2. Pinch-to-zoom to change the page size, and drag to pan.  On tablets I want to be able to zoom in arbitrarily on a page.

Not sure how easy this would be to do, but I feel like I've seen other web apps do this.

**Comment by ajslater** [comment]
I believe I have swiping/touch page turns turned on when the viewport is > 768px. The idea was a crude gate for some larger tablets, but not phones.

zoom & drag is undoubtedly a useful feature, but i'm going to punt that for later.

**Comment by beville** [comment]
Just following up this, on both my tablets (Samsung and iPad), the only swipe gesture that seems to do anything is when I swipe right-to-left on the right side of the screen.  That brings the "Reader Settings" sidebar on the right into view.  I've never gotten page-turn swipes to work.

**Comment by ajslater** [comment]
Release 0.13.0 has a possible touch fix for swiping pages in the comic reader.
Only active on medium sized tablets and larger.

**Comment by ajslater** [comment]
release v0.14.0 introduces sliding animations for changing pages. As part of this it removes my (janky?) manual touch system and uses the vuetify library's touch/swipe system for changing pages.
pinch to zoom seems to work okay-ish and not activate page turning in my tests.
