### ISSUE TITLE
OPDS notes

### ISSUE THREAD

**Issue by beville** [ajslater/codex#189]
Very cool to see OPDS added! I've not used it much so was playing around with it on Codex with some different clients, and also seeing what some other comic servers like Komga, Kavita, and Ubooquity do, and wanted to share some thoughts.

For clients I was looking at **Panels** and **Chunky**, and also two other programs which are not great comic readers, but are relatively sophisticated OPDS clients:

-  **PocketBook** iOS app: It's not obvious, but if you select "Books" on the bottom nav bar, and then select the globe icon, it brings up a list of "Network Libraries" and you can add new OPDS feeds here.   PocketBook supports searching feeds, but doesn't seem to support facets.  
- **Foliate**, a Linux GUI app.  Also not a great comic reader, but its OPDS browser is the richest I've seen so far.  It seems to support facets and searching. (Though the facets/filters stuff is not 100% clear to me.)

In addition to the comic servers, it was interesting to see how other public OPDS feeds look.  I'm sure you were probably using some of these as refereces already

- **Feedbooks** (https://catalog.feedbooks.com/catalog/index.atom)
- **Project Gutenberg** (https://m.gutenberg.org/ebooks.opds/)
- **Internet Archive** (http://bookserver.archive.org/catalog/)
 
Way too many permutations of things to be exhaustive, so just some observations on what would enhance Codex's OPDS experience in a practical way:

1) **Top Level Menu Needed** -  All of the other feeds and servers I looked at have a simple top-level 'menu' feed, with different views on the catalog. Even the ones that provide some facet-y stuff, like Feedbooks, do this.  I think Codex would benefit from that that.  I think I saw you mention adding a "Recently Added" that would go well here.
2) **Facets are Confusing** - Or at least they are for me.  Foliate is the only app that I think supports them (with its top bar browser), and the only feeds I see that provide them are Feedbooks and Gutenberg.  When I'm browsing Codex in Chunky or Panels, and try to go the sub-choice of series view, I end up with a short sub-set list of the actual series with the publishers list still there. In Foliate it's a different experience, but still confusing. (Might be the that app's fault though) I wonder if supporting facets might not be worth it right now?
3) **No Thumbnails in some clients** - The thumbnails work in Panels, but not in PocketBook or Foliate.  This isn't a huge deal, but might be something to look into.  
4) **Search works great!** - Not an issue, but wanted to mention that in Foliate and PocketBook, I can search for keywords (i.e. "Kirkman" or "Nolan"), and get lists of issues.  This doesn't work at all  for the other server apps.
5) **Better Metadata Synthesis needed** 
    - I find that after seaching in the search-capabable apps, I got lists of results with no thumbnails, and no series names, so I might see a list with results like "#⁠006", "#⁠012" and "#⁠508 Mortal Remains".  It might be more useful to prepend the series name to the issue number.  (And maybe optionally not include the issue title?) This would also be needed for other lists that aren't in context of the series, such as "Recently Added".  This applies also to what I'll call the "issue view" in these apps where there is a stand-alone window/screen that shows the details of the book/issue but lacks the series name.
    - Also for the "issue view" window, consider populating the publisher field, and for the other ComicInfo.xml data that doesn't have a real home in OPDS, maybe synthesize a more complex description to include creators, imprint, web link, etc.  (Actually, I just noticed that Komga does seem to populate some creator info in the author fields.  But I don't know that's the right way to do it, since comics have more complex creator details that prose books, and it might be better to put that into into the general description.)
6)  **Download** I just realized that on PocketBook there's no way to actually read/download the comic from the Codex OPDS feed. Komga seems like the only one to work with PocketBook in this respect.

Sorry, if this is all bit much.  It's just I'm a big fan of Codex.  Unlike the others I've mentioned here, it really fits with the way I organize comics (which is to say not at all!), and pefer a more US-centric (as opposed to Euro or Manga) expectation on series/volumes/issues.

Let me know if I can clarify any of this or provide example screenshots, etc.

Thanks again for all your work on this!

**Comment by ajslater** [comment]
This is an astonishing amount of data, suggestions and enthusiasm. Thank you so much. I could never have found this much OPDS information myself. I'll definitely pour through this for the next release.

"A Most Recent" facet / top link for OPDS is already implemented in the develop branch, but I'll be sure to review all these suggestions.

**Comment by ajslater** [comment]
v0.13.0 has a great deal more metadata in opds. Tested with pocketbook reader and has fixes the pocketbook bugs you pointed out.
Regrettably I haven't gotten a linux desktop up and running to test Folate, but i'm intrigued as it sounds like it implements more of the opds spec than many alternatives.

1. Top Level Menu Needed
v0.13.0 should have a couple more top level links included as entries for most clients. "Newest Issues", "Oldest Unread", as well as a "Start / Home" link.
2. Facets are Confusing
Facets are conceptually easy. They're filters and orders on the current view, which applies nicely to how the Codex browser likes to work. However, the implementation of facets on most clients is missing or abysmal. Henceforth, facets are only turned on for clients that are known to support them well (Kybooks 3 right now) and their functionality is replicated by injecting entry links into the feed instead for all other clients.
3. No Thumbnails in some clients 
Got some fixes for this. Check it out.
4. Search Works Great!
I wonder if the other server apps limit themselves explicitly to searching on the OPDS specific metadata tags. Which while technically correct, would lead to unsatisfactory results for many feeds.
5. Better Metadata Synthesis needed
Much more metadata available in OPDS for v0.13.0. 
Many of Codex's tags are lumped into OPDS's narrow <categories> tag so clients can display them as they see fit.
Clients implement a some of these metadata tags and not others and display them in various ways.
Your suggestion to force metadata into the <content> tag and display it with text how I see fit has merit, but I didn't do it.
6. Download
Fixed for pocketbooks. Some of these clients are real particular about mime types.
