### ISSUE TITLE
Settings for all comics doesn't apply to current comic

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#19]
Adjusting options for the current comic using the All Comics setting doesn't apply to the current comic.

![options](https://user-images.githubusercontent.com/17379660/91627807-04d60d00-e96f-11ea-9533-bcfae18b2691.gif)

**Comment by hubbcaps** [comment]
Additionally, it seems settings for All Comics doesn't persist at all or seem to do nothing at all.

**Comment by hubbcaps** [comment]
All comics settings works for setting the settings on the current comic but still doesn't seem to stick around for all issues after setting them, jumping to a different issue just uses the default settings.

**Comment by ajslater** [comment]
fixed
