### ISSUE TITLE
Center displayed comic page

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#20]
Currently the comics are slightly left centered which gives a kind of uneasy feel to reading, perhaps center the page?

![image](https://user-images.githubusercontent.com/17379660/91627857-5a121e80-e96f-11ea-8bf7-f8aead391734.png)

**Comment by ajslater** [comment]
Fixed in v0.5.7 https://github.com/ajslater/codex/pull/36
Although I'm still not happy with two page positioning.
