### ISSUE TITLE
install information from linux mint 21

### ISSUE THREAD

**Issue by rmleonard** [ajslater/codex#207]
[codex-install-output.txt.tar.gz](https://github.com/ajslater/codex/files/10225004/codex-install-output.txt.tar.gz)
[codex-build-steps.txt.tar.gz](https://github.com/ajslater/codex/files/10225008/codex-build-steps.txt.tar.gz)

this is neither a bug needing to be tracked nor a feature to be requested..
this is logged output and as clear as wet mud.
but it should prove useful? I hope

**Comment by ajslater** [comment]
thanks!
