### ISSUE TITLE
Load Time Issues

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#21]
Currently there doesn't seem to be any pagination, so if you end up in a folder with quite a few issues, you end up trying to load all of the cover images at once, leading to both initial lag as it gathers up all the issues its supposed to display and then again in the loading of the individual images.

Perhaps some pagination may help in this regards, with a setting for how many issues people would like to have displayed per page?

**Comment by ajslater** [comment]
There is now pagination in v0.5.7 https://github.com/ajslater/codex/pull/36
Give it a whirl.
