### ISSUE TITLE
Sort option for issue numbering

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#22]
Currently this request **should** ideally be fulfilled by Date Published, however something is occurring to separate issues within a series, see attached. 

The addition of the number 1 next the comic name seems to be seperating them from the ones who don't have this additional numbering.

By sorting on just straight up issue numbering, I believe this can be avoided.

![image](https://user-images.githubusercontent.com/17379660/91629413-d875bd00-e97d-11ea-8c3f-20dcf48a6eb3.png)

**Comment by ajslater** [comment]
Could you double check that the dates that seem out of order are indeed in the wrong position?
It occurs to me that displaying the field sorted by in the browse tile would remove the mystery about whether this is a bug or not.

**Comment by hubbcaps** [comment]
Pretty sure, we can see here a pretty sharp jump in numbering

![image](https://user-images.githubusercontent.com/17379660/91789992-98ece200-ebc4-11ea-9177-c00426f3a056.png)

Then shortly below we can see it sort of reset when that "1" comes into the title there

![image](https://user-images.githubusercontent.com/17379660/91790038-adc97580-ebc4-11ea-9c3f-1734bdae02c0.png)


The metadata difference between one of the titles without a "1" in the title

![image](https://user-images.githubusercontent.com/17379660/91790088-c5086300-ebc4-11ea-940a-91b770efd868.png)


and one with the "1" in the title

![image](https://user-images.githubusercontent.com/17379660/91790127-dc475080-ebc4-11ea-95ae-97a1e187cc6d.png)

**Comment by ajslater** [comment]
v0.5.9 will display more data in the browser to help us determine if the sort is really bad or not.

**Comment by hubbcaps** [comment]
So for comics that have a volume like seen here in there metadata, everything is good, but as we can see if they don't have meta data like volume, it ends up putting them after everything that does have the metadata.

In the case where using Folder view, might it be better to use the name of the file on disk rather than the name you're giving it via Codex?

![image](https://user-images.githubusercontent.com/17379660/92317849-36c42080-efba-11ea-9191-d41b18246964.png)


Another interesting issue that can occur when sorting by something like Date Published is if the metadata isn't there it defaults to a name based sort it seems like, which is cool but maybe something better could be done to try to possibly guess the position based on issue number? Might require some weird parsing that might not be worth it, but possibly something to look into. Definitely more of a collection issue in not having that metadata available more than its an issue with Codex itself since the feature actually works if you're providing good data for it to use

![image](https://user-images.githubusercontent.com/17379660/92317924-c8339280-efba-11ea-9ffe-d115d91bcd5b.png)
