### ISSUE TITLE
log line - JSONDecodeError Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#237]
Running v1.1.16 on Unraid.  Noticed during import a log line for a file including `JSONDecodeError Expecting value: line 1 column 1 (char 0)` during the `Read tags` phase.  

Not sure of any actual problem, but that the error is there is reason enough to bring it up.

It comes with a filename when it happens.  Happy to share in private.

**Comment by bmfrosty** [comment]
Apologies.  Forgot to note that the errored files do get imported.

**Comment by ajslater** [comment]
I'm curious. Were the misbehaving files pdfs?
I've just fixed a version of this bug in the next release for pdf with bad
magic numbers. I'm now detecting pdfs via file extension as well.

**Comment by bmfrosty** [comment]
CBR and CBZ files.  No PDFs, but I don't have a lot of them.

**Comment by bmfrosty** [comment]
Stopped happening when I stopped using Unraid's shfs merged directories.   This does not appear to be a Codex issue.
