### ISSUE TITLE
[Feature Request] Allow libraries to represent multiple directories

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#239]
I'm sure this is on a long todo list of yours, but I'll put it here anyway.

I'd like to be able to have a library that is made up of multiple directories.

Instead of having 4 libraries that are like:

/mnt/disk1/Comics/Comics/
/mnt/disk2/Comics/Comics/
/mnt/disk3/Comics/Comics/
/mnt/disk4/Comics/Comics/

Instead have those represented by a single library.

**Comment by lordwelch** [comment]
One thing that might be an option for you as a workaround is using overlayfs.
Here is an example fstab
```
/dev/disk/by-label/disk1 /mnt/disk1  ext4    defaults,noatime,nofail 0 2
/dev/disk/by-label/disk2 /mnt/disk2  ext4    defaults,noatime,nofail 0 2
/dev/disk/by-label/disk3 /mnt/disk3  ext4    defaults,noatime,nofail 0 2
/dev/disk/by-label/disk3 /mnt/disk4  ext4    defaults,noatime,nofail 0 2
overlay                  /mnt/Comics overlay defaults,noatime,nofail,redirect_dir=on,index=off,metacopy=on,lowerdir=/mnt/disk1/Comics/Comics/:/mnt/disk2/Comics/Comics/:/mnt/disk3/Comics/Comics/,upperdir=/mnt/disk4/Comics/Comics/,workdir=/mnt/disk4/overlay-work/,x-systemd.requires-mounts-for=/mnt/disk1/Comics/Comics/\040/mnt/disk2/Comics/Comics/\040/mnt/disk3/Comics/Comics/\040/mnt/disk4/Comics/Comics/ 0 2

```

You can leave off the upperdir to make it read-only, but it only really supports editing/adding files with a writeable upperdir and going through the combined mountpoint.
I have my setup like this and manually distribute the files back to the lowerdirs every once in a while (when I run low on storage or about 1/year) and do a reboot to make sure it finds everything

**Comment by bmfrosty** [comment]
@lordwelch I was doing a version of that before (Unraid's version of it) and it resulted in some problems importing.  I'm honestly looking for a feature that others may find useful instead of something that others who may be less comfortable in /etc/ could find useful.  I am going to try your solution though too.

**Comment by ajslater** [comment]
Currently the workaround for this is would be to make many libraries and give them the same settings.

I'm gonna leave this ticket open to think about it, but it's not a feature that's likely coming soon.

**Comment by ajslater** [comment]
No plans to implement this
