### ISSUE TITLE
OPDS authors have "i" appended to names.

### ISSUE THREAD

**Issue by beville** [ajslater/codex#245]
This is a super minor bug, but I've noticed in different OPDS browsers that show this info, the names of authors have an "i" appended to each of them.  Such as "Robert Kirkmani"  (It sort of makes all the names seem vaguely Turkish to me :smile: )

Attached screenshot from PocketBook app

---

![unnamed](https://user-images.githubusercontent.com/7294848/221074219-47bae854-cd9d-45dd-bd9d-4662467c78f4.jpg)

**Comment by ajslater** [comment]
Consequence of using neovim as my primary editor. Thanks. Sigh.
Fixed.
