### ISSUE TITLE
[Feature Request] Have OPDS include the series title when browsing

### ISSUE THREAD

**Issue by beville** [ajslater/codex#246]
(Last one for now, I promise!)

The series title is already included in when browsing OPDS in the "New Issues" view, but would also be welcome in the "Folders" view as well, as files in the folders may lack the context of a series.  

In addition, even when in the context of a series, it's kind of needed for some apps, like Panels, because when I download one random issue of a comic, it might show only "#2" for the downloaded comic.  Having it show "Whiz Comics #2" anywhere in the browsing tree would be nice.  Perhaps this could be optional behavior?

**Comment by beville** [comment]
If there was an OPDS listing option created for showing series names, another related idea would be to toggle on and off showing volume and issue title.

This could provide for custom OPDS listing verbosity for a given user:

    "#2"
    "Smash Comics #2"
    "Smash Comics #2 v1952"
    "Smash Comics #2 v1952 - The Smashening"

**Comment by ajslater** [comment]
Should be in v1.2.4
