### ISSUE TITLE
[Feature Request] Add hotkey to flip reading direction - manga mode.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#248]
As the title says.  When in read mode, if I'm reading manga, I want to read right to left - I want left to move me forward a page and right to move me back a page.  Two page mode should also put the lower page on the right and the higher page on the left.

**Comment by ajslater** [comment]
This was crazy. Reversing some things and other things lead down some weird rabbit holes and UI designs. I've got a thing now called Reverse Mode in v1.2.4

It's intended to let you read manga LTR. The setting is durable and has global default options as well.

**Comment by bmfrosty** [comment]
I will be testing as soon as I get my library rebuilt again.  You've inspired me to reorganize multiple terabytes of comics.

**Comment by ajslater** [comment]
As I'm not a regular manga reader, i don't have confidence that this is the correct solution, but it's a starting point.

**Comment by bmfrosty** [comment]
Seems to work really well.  I have no complaints.
