### ISSUE TITLE
Add option to download comic issues

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#25]
The ability to download comics for sharing or use outside of Codex itself would be a nice addition as well.

**Comment by ajslater** [comment]
Already exists, but is hidden in the metadata "edit" pencil menu. I should probably add it to the browse menu for comics.

**Comment by hubbcaps** [comment]
Ahh there it is! Yeah, seems like a general option that might be more useful is displayed a bit more prominently outside of the edit section.

**Comment by ajslater** [comment]
Fixed in v0.5.7 https://github.com/ajslater/codex/pull/36
Included in the browse tile triple dot menu.
