### ISSUE TITLE
[Feature Request] Display additional relevant data when waiting for the filesystem to stop changing.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#254]
I get the following occasionally on filesystems that don't have anything going on:

`2023-02-27 20:28:16 PST WARNING Import apply waited for the filesystem to stop changing too long. Try polling again once files have finished copying.`

When spitting out that error message, can the name of the  and some other relevant data be printed as well?

**Comment by ajslater** [comment]
I've added the library path to this warning message. Unfortunately it's not yet practical to name offending file(s)

**Comment by bmfrosty** [comment]
Thanks!
