### ISSUE TITLE
[Feature Request] Improve the predictability of the top level of folder mode.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#256]
I've been poking at this for a while and it feels like sometimes I get the top level to show me individual libraries, sometimes it gives me a meta-library that shows me every folder within all of the libraries, and sometimes it shows me both.

I get the desire for a meta-library in folder mode, but a more predictable way might be more user friendly.

Here's the proposal.

1. Top level of folder mode is a list of individual libraries
2. In addition to individual libraries, it should show an icon for a meta-library
3. Add a per-user option to show the top level as a meta-library

**Comment by ajslater** [comment]
Top level folders should be the top folder added to the library and nothing else. This seems like a bug.

**Comment by bmfrosty** [comment]
That would explain the inconsistency.  I wasn't sure what the intended was.

**Comment by ajslater** [comment]
This was an old bug originally reported by ToxicFrog. It happens when folders are moved.
Fixed again. Not sure how it got unfixed.
