### ISSUE TITLE
[Feature Request] Add options to not use thumbnails.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#258]
When the server is disk or cpu is under heavy load it can take a significant amount of time to browse the library.  Part of that is retrieving and loading thumbnails.

Add options to use generic icons instead:

1. Use thumbnails for both folders and issues. (current behaviour)
2. Use generic icons for folders, but use thumbnails for individual issues.
3. Use generic icons for both folders and issues.

**Comment by ajslater** [comment]
This is unlikely to be done.
There is some cpu activity creating thumbnails the very first time the a browser requests them. How many at a time depends on the size of your browser viewport.
But it's a one time cost. After that Codex serves the created thumbnails from disk at minimal io cost.

**Comment by bmfrosty** [comment]
Ah.  I was wondering.  I'm digging through my SSD and I only see 900ish covers.  I was wondering if it could be DB access times, but that's all on my SSD as well.   Once things settle down with all my reorganizing, I'll test again.
