### ISSUE TITLE
Does Volumes view work?

### ISSUE THREAD

**Issue by beville** [ajslater/codex#263]
This is something I've not tried before, but with the fake library, I noticed that the "Volumes" view in the web UI isn't acting as I expected.

I have a fake library where every series has 2 volumes of 10 issues each.  I would have expected the Volumes view to have a thumbnail for each separate volume of 10 issues, but instead it looks like it just has entries for the series, each with counts of 20. When I drill down into the series, I see both volumes represented.  The color of the generated covers makes this really distinct.

The generated library has 20000 comics, with 1000 series, and each series has 2 volumes of 10 comics each.  There should be 2000 volumes listed in the stats, but instead I see:
![image](https://user-images.githubusercontent.com/7294848/222940877-e3be8973-fef0-4b68-8b30-43ea3644a46b.png)

**Comment by ajslater** [comment]
This is a bad bug. Thanks for pointing it out. Fix incoming.

**Comment by ajslater** [comment]
Fixed in v1.2.8 requires re-importing the comic to populate the database.
Recommended to Force Re-Import all libraries to preserve bookmarks.
