### ISSUE TITLE
Admin Panel Users Last Login should show last opened session

### ISSUE THREAD

**Issue by ojmaster** [ajslater/codex#265]
In the Admin Panel -> Users, the last login column shows when last the user had actually logged into their account. I was wondering if this was meant to show when last the user had opened a session (gone to the link), because browsers will keep you logged in even after you close them. If not, I was wondering if you could make this a separate column then as it would be nice to see when the last time a user had actually gone to the website.

**Comment by ojmaster** [comment]
to add onto the analytics tracking, would it be possible to add a place to add google analytics code

**Comment by ajslater** [comment]
"last active" is a possible feature for the future. thanks for the suggestion.

i'm less inclined to add third party analytics insertion.

**Comment by ojmaster** [comment]
Last active makes more sense yeah, also understandable about the third party analytics. But if not third party do you have any plans for more analytics in the future? I understand that this is meant to be just a reader, but I did have an idea where users could leave ratings on issues or series that could be publicly seen by other users or guests as "reading recommendations", stuff like that would be cool as I am hosting codex for me and a bunch of friends and leaving little things like that definitely would be a nice feature. Again I understand that it's simply a reader but yeah.

**Comment by ajslater** [comment]
added as of v1.2.9
