### ISSUE TITLE
Codex names all Chunky downloads as "download"

### ISSUE THREAD

**Issue by beville** [ajslater/codex#273]
I notice that on Chunky all files when downloaded from Codex are named "download.cbz". 

This is an issue because Chunky seems to have an optimization that when you go to look at comic in the feed, I think it's checking the download filename vs what it's already got, and just jumps the reader to that file in the local library, which is named "download".  So once you download a file from Codex, it think that it's got _all_ files in the feed, and you can't read or download anything else.  

If I use the Chunky UI to change the file name, I can download another one. 

Maybe Codex could rename the download file based on metadata, or at minimum some GUID-like string

**Comment by ajslater** [comment]
This should be fixed in codex v1.3.0

**Comment by beville** [comment]
Looks good as of 1.3.5.  Thanks!
