### ISSUE TITLE
[Feature Request] When in 2-page mode, and an image is wider than it is tall, display it alone like a cover.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#276]
See attached screenshot for example of what this looks like now.

![Screen Shot 2023-03-15 at 2 28 24 PM](https://user-images.githubusercontent.com/31758/225448127-2a0557c0-b981-488d-9202-de201a64e8e4.png)

**Comment by ajslater** [comment]
This is should now happen with[ v1.5.0](https://github.com/ajslater/codex/releases/tag/v1.5.0)
