### ISSUE TITLE
[Bug] Last Active Date incorrect

### ISSUE THREAD

**Issue by ojmaster** [ajslater/codex#278]
The Last Active column is showing the incorrect date![image](https://user-images.githubusercontent.com/62865062/226151078-2b021861-7d7a-4562-bace-45daae8d20c4.jpeg)

Today is March 18th, it is showing the date as March 19th, however the actual time seems to be correct.
I have my timezone correct as well

**Comment by ojmaster** [comment]
this is showing up in all date fields, the day seems to be one day ahead

**Comment by ajslater** [comment]
Should be fixed in Codex v1.3.1
