### ISSUE TITLE
Feature Request:  Add "Jump to Series" link for issues

### ISSUE THREAD

**Issue by beville** [ajslater/codex#291]
From the "would be nice" files:

Not sure if this fits the paradigm of the UI, but sometimes, if I'm viewing an single issue, I'd like to quickly jump to the series to the see the other books.  

A logical place might be to add it to the metadata page where the series name would be a link.  Like I said, I'm not sure if it fits the vision of the way things should work, but something along those lines would be handy.

**Comment by ajslater** [comment]
Hmm. you know I have this janky series counter in the upper left of the
reader. I don't like where it is and how it looks, but i wanted a way to
see that i was on issue 4/16.

Maybe that becomes a button.

**Comment by ajslater** [comment]
Added in the tags/metadata dialogue in v1.3.7
Thanks for the idea!

**Comment by beville** [comment]
Thanks for implementing it!  I like the folder and volume links too.

I _have_ noticed some flakiness, maybe dependent on browser or caching, but haven't really characterized it.  I'll give it a closer look soon and maybe have more detailed notes on what I'm seeing.
