### ISSUE TITLE
Can't find failed import file but can see alert.

### ISSUE THREAD

**Issue by tehguitarist** [ajslater/codex#295]
Hopefully this is just me being a bit dim. I just can't seem to find where the list of failed imports is, I can see I have one in my library, but can't for the life of me work out what it is. 

I'm sure i'm just missing something obvious, but I can't see anything in the admin console.

**Comment by ajslater** [comment]
if you click on the Failed Imports bar under the Libraries tab, it should expand into a list of failed imports. A UI decision where perhaps I tried to hide too much.

**Comment by tehguitarist** [comment]
Perfect! Was just a bit blind. Appreciate the response.
