### ISSUE TITLE
[Feature Request] Custom thumbnails

### ISSUE THREAD

**Issue by ojmaster** [ajslater/codex#299]
I was wondering if it could be possible to set custom static thumbnails for groups such as Publishers and Series, I would like to have variant covers be set for some of my series or even have the publishers logo set for when looking through all my publishers

**Comment by ajslater** [comment]
This has been asked for a couple times before. I'm gonna leave this ticket open to remind me to maybe implement it.

**Comment by ajslater** [comment]
This feature is included with [Codex v1.6.0](https://github.com/ajslater/codex/releases)
