### ISSUE TITLE
OPDS Suggestion: Page or item limit for feeds.

### ISSUE THREAD

**Issue by beville** [ajslater/codex#303]
For the 'sorted' feeds currently offered (Recently Added, Oldest Unread) they are really just the entire list of comic issues, sorted in a particular way.  When it's a very large list (10K+), some clients seems to struggle. 

Chunky, of course, is trying to do client-side sorting, so it's attempting to load the _entire_ feed before it renders it, and that always times out.  But even Panels, which seems to be doing page-fetch-then-render is seems to still be running the fetch process in background and it's slowed down by all that background activity.

Granted, these are client implementation problems, but I would argue that there is not much utility for some feeds like this beyond a certain number issues, maybe 100 or so.

My thought is to create add a new OPDS feed param to limit the number items (or pages) before it stops creating a "next" link.

**Comment by ajslater** [comment]
OPDS special top links are now limited to 100 entries.

**Comment by beville** [comment]
Awesome!  Noticeably better performance when going to those feeds.
