### ISSUE TITLE
Feature Request: Sorting By Recently Read

### ISSUE THREAD

**Issue by beville** [ajslater/codex#304]
It would be cool to be able to open a random book in the web UI, and then find it easily in the OPDS feed, or vice versa.

Not sure it you're already tracking it, but adding a "Recently Read" sort option for both the web and a new feed OPDS would be pretty neat.  This would include both completed or in-progress books.

**Comment by ajslater** [comment]
As of codex v1.3.11 Web UI now has a `Last Read` order by option.
OPDS 1 now has a Last Read top entry that sorts this way as well.
