### ISSUE TITLE
OPDS Popup Copy Doesn't Work

### ISSUE THREAD

**Issue by beville** [ajslater/codex#305]
This is super minor, and maybe I misunderstand it, but when I bring up the OPDS feed dialog, it says "Copy OPDS URL to Clipboard" when I hover.

![image](https://user-images.githubusercontent.com/7294848/235315036-51c931ae-af5a-46c0-a2b5-d1599a0a68fd.png)

Is it supposed to auto-copy the URL on click/touch?  I've don't this had this work for me or various platforms.

**Comment by ajslater** [comment]
It is supposed to work. I just tested it working on MacOS Chrome, Firefox, and Safari. And iOS Safari.
I'd be interested to hear which platforms its not working on. 
Sometime browsers disable clipboard access outside of HTTPS connections.

**Comment by beville** [comment]
Ah, that’s probably it.  I’ve never set up a reverse proxy for https.  Just been accessing Codex on my local LAN.  I’ve mostly tried with iOS Safari, Android Chrome, and Linux Firefox.

**Comment by ajslater** [comment]
Since it's easy to check the url scheme, codex v1.3.12 does not display ui implying that clipboard functionality exists outside of https.
