### ISSUE TITLE
Story Arcs

### ISSUE THREAD

**Issue by potter-jason** [ajslater/codex#318]
I see with the latest version, you've added some additional Story Arc support, awesome. Do you think it will be possible to add Story Arc to the "TopFolder" drop down menu, which would invoke sorting the library by Story Arc as the top category in the hierarchy, followed by Story Arc Number that you added recently?

**Comment by ajslater** [comment]
This is an interesting idea.
It's currently possible, sort of, by selecting series or issue as a top group, selecting one story arc and then ordering by story arc, but it would be nice to be able to browse by story arc.

I think i might give this a try, thanks for the suggestion.

Unfortunately, there isn't much SeriesArcNumber tagging around, so it's full power may have to wait for further tagging or reading list improvements, but I'll be ordering by (StoryArcNumber, Published Date, Issue Number) as fallbacks. So may look okay.

**Comment by potter-jason** [comment]
I believe the gamespot api that all the tools use has a way to query by story arc and get an issue list by story arc. 

This is the main story arc record - 
https://comicvine.gamespot.com/avengers-vs-x-men/4045-56674/

And this is the list of issues -
https://comicvine.gamespot.com/avengers-vs-x-men/4045-56674/issues/

**Comment by ajslater** [comment]
Implemented this idea in Codex v1.4.0. Thanks for the idea!

**Comment by potter-jason** [comment]
By the way, thank you, I noticed a while back the Story Arc tab and use it all the time. Loveit
