### ISSUE TITLE
Group cover showing random covers?

### ISSUE THREAD

**Issue by ojmaster** [ajslater/codex#324]
Normally if I'm ordering by name, the cover for the group (publisher, series, etc) would be the first result, but now it's just a random cover that isn't even the top of the list? Is this intentional?

**Comment by ajslater** [comment]
is this still a problem with [v1.5.0](https://github.com/ajslater/codex/releases/tag/v1.5.0)?

**Comment by ojmaster** [comment]
@ajslater yeah this is still happening, its only with group by publisher though, it uses a random issue's cover  
![image](https://github.com/ajslater/codex/assets/62865062/26afd9d4-253f-4418-8092-bdb95f59cfc3)

**Comment by ajslater** [comment]
I think this is fixed in [v1.5.2](https://github.com/ajslater/codex/releases/tag/v1.5.2)
Thanks for reporting!
