### ISSUE TITLE
Potential future focus

### ISSUE THREAD

**Issue by vonguard** [ajslater/codex#337]
Hey there, this is a feature request I suppose, but it's more of a strategic request, really. There are a lot of book servers out there, and I like Codex a lot, so I wanted to offer some strategic advice for how it could continue to grow and fill a niche that remains unfilled in the comics server world.

So, I used Ubooquity for years, and I love its responsiveness. I hated its stability. Recently, Ubooquity's author is back on the project, and is working on version 3.0. The docker containers have started to update the 2.0 containers to Java 17 or something... They were Java 8.

So now, Ubooquity is a little more resilient, and a little faster. But at the end of the day, it seems it's still single-threaded for ingesting a library. Ubooquity can take days to ingest a huge library. Codex, on the other hand, can do this in an hour or two. This is probably Codex's strongest advantage over other comic servers.

Additionally, Ubooquity loves to choke on cbrs labeled as cbzs, and vice versa. It doesn't even try to unzip a cbr if it seems "corrupted." I end up having to convert all these CBRs I find in the logs to CBZs and read them. Plus, Ubooquity can still find comic files that will cause it to lock solid and need a restart. Thankfully, I think the move from Java 8 to 17 has removed the bug where restarting a hung server would corrupt the comics database, causing you to start over, but who knows, that could still happen!

Another competitor is Kavita, which is focused on manga. This server goes too far in the other direction, and when scanning and ingesting, it will absolutely red-line your CPU, which is not what I want to see for 24 hours on my server. I never push it that hard, and I don't want to. Kavita is also completely terrible at American comics, and only wants manga.

So that leaves Codex in a sweet spot where it needs to do one thing to become the only possible choice: increase responsiveness of the browser experience. I think Ubooquity accomplishes this by using some highly optimized, very mature Java libraries and components. That's where the Java shines through for it. Codex has all the best server-side features I want, but the responsiveness overall is not up to Ubooquity's standards. But that's OK, because Ubooquity is poorly engineered at present, and crashes a lot and takes forever to ingest libraries.

So, if you're feeling up to a challenge and a new goal, I highly recommend speeding up the browser experience so that it's much faster to scroll through comic listings and directories. Given some optimizations there, this platform could easily become the Plex of comics. Your competition has left a big hole for you and with a few months of work, you could definitely speed past them. And who knows, maybe you could offer Codex as a service hosted on Digital Ocean, so people can pay an up-charge on DO fees to pay you to auto-host their libraries!

Thanks for this great software. I'd imagine there are libraries and.... god I hope it doesn't require a whole framework.... to speed up the web experience. I know it's a big undertaking, but I recommend installing Ubooquity to see just how fast that interface can go when it's not crashing and corrupting everything. The Linux Containers Image server has an updated docker file to check out.

**Comment by ajslater** [comment]
Thank you for the kind words. Codex was started because Ubooquity didn't support bookmarks long ago and wasn't open source. I'm fairly sure (with no numbers to support this idea) that Codex is the third most popular comic reader behind Komga and Kavita. The authors of both those programs are cool guys and we talk and trade ideas from time to time.
The library import speed improvements were done after some feedback from the good people on the Mylar support channels.

I'll be sure to check out the new ubooquity.

I'll take a look at the library browser and see if I can find some speedups, thanks.
