### ISSUE TITLE
[Feature Request] Zoom in browser comic reader

### ISSUE THREAD

**Issue by BenMcLean** [ajslater/codex#339]
Codex's browser comic reader should allow some way to zoom in and out to magnify parts of the image being viewed.

The intuitive way would be for zooming in and out to be activated when holding down ctrl and turning the mouse scroll wheel, but that might not be possible in the browser. If that can't be done in the browser then some other key combination should be possible however.

**Comment by ajslater** [comment]
Aw damn. I wasn’t gonna add features for a bit but I do this all the time
on mobile and now you’ve captured my interest.

**Comment by BenMcLean** [comment]
It's really an accessibility feature cause O have low vision. Thanks for considering this because it would make a big difference for me.

**Comment by ajslater** [comment]
[v1.5.0](https://github.com/ajslater/codex/releases/tag/v1.5.0) includes a zoom feature by double-clicking.

I really thought this was going to be a quick feature, but then i learned how broken css zoom and css transform: scale() are in all browsers. Ah well, I fixed it with javascript eventually.

**Comment by BenMcLean** [comment]
Looking at the live demo server, I can see how you can sort of zoom in a little, if it's to a part of the page that it kind of lets you zoom in, but you can't zoom in anywhere on the page because that makes you switch pages sometimes, and also you can't scroll around within the page at all once you're zoomed in.
But it's a good start though, it just isn't quite what I'd call usable yet.

**Comment by ajslater** [comment]
The way I was using it was to zoom using the middle third of the page and
then scroll up down left and right once the picture size exceeded the
viewport size. Then maybe zoom more if you wanted more zoom.

Are you saying you're having trouble scrolling once zoomed in?

I'd considered removing the page turning bars while zoomed in, but decided
it seemed unnecessary.

**Comment by BenMcLean** [comment]
> Are you saying you're having trouble scrolling once zoomed in?

Yes -- mainly scrolling horizontally.

> I'd considered removing the page turning bars while zoomed in, but decided it seemed unnecessary.

I think when you click and drag the mouse, it'd be good if that would scroll around both vertically and horizontally.

The ideal behavior would be just like CDisplayEX on desktop, but I realize that it's tricky to get that same result on web.

**Comment by ajslater** [comment]
Thanks! The issue is me. I haven't used a mouse in years and neglected to test with such.
You can now drag to scroll horizontally with a mouse in [v1.5.2](https://github.com/ajslater/codex/releases/tag/v1.5.2)
Confusingly, vertical scroll is still done with other methods like the mouse wheel or side bar. I acknowledge that this isn't ideal from a UX perspective but it should work.

**Comment by BenMcLean** [comment]
OK I think the new version is definitely an improvement. What happens in this new build on FireFox is that Clicking and dragging doesn't actually work to scroll horizontally but you kind of click to activate the horizontal scrolling mode and then it kind of starts following your cursor location and once it starts doing that, there's no clear way to make it stop, which you'd want to do when it's time to go on to the next page to keep reading. Like I said, I don't have a lot of web dev experience so I'm not sure how good I can expect it to be but the way it doesn't do actual dragging was unexpected to say the least.

I would definitely suggest testing mouse control related features with an actual mouse.

**Comment by ajslater** [comment]
Ah yes I see. I'd only tested this with chrome and safari. Firefox does
have bad behavior with this solution. I'll see if i can fix it.

**Comment by ajslater** [comment]
Firefox has special drag behavior for only for img tags and will interrupt other events unless `<img draggable="false" />` is set.
[v1.5.3](https://github.com/ajslater/codex/releases/tag/v1.5.3) should fix this.

Found me an old Razer mouse in a drawer and now i'm draggin' and clickin'.
