### ISSUE TITLE
/tmp getting filled with tmp*.rar files

### ISSUE THREAD

**Issue by barbequesauce** [ajslater/codex#34]
presumably related to the exceptions in issue #33

**Comment by ajslater** [comment]
oh weird. Neither Codex nor [Comicbox](https://github.com/ajslater/comicbox) (the library that handles archive operations),  use /tmp for anything specifically. I wonder if python rarfile is misbehaving somehow.

**Comment by barbequesauce** [comment]
Confirmed related to #33. ID10T errors.
