### ISSUE TITLE
Failed Searchs Give Invalid Results 

### ISSUE THREAD

**Issue by beville** [ajslater/codex#355]
This is something that's been confusing me for a while, especially since my library/host machine combo is slow for some Codex features, but I just was playing with Panels' search feature, and then just with OPDS URL fetches, and I see this.

Basically if a I give a search that should have no hit, it gives back a list of what seems to be *all* comics.

Examples:

*  `series:'The Walking Dead' credit:Moore`
     returns only the issues of that series that Tony Moore worked on, as expected.

* `series:'The Walking Dead' credit:Bendis`
    returns what looks like the every issue in the library, sorted alphabetically, when I expect an empty list

**Comment by ajslater** [comment]
This should be fixed in [v1.5.8](https://github.com/ajslater/codex/releases/tag/v1.5.8)
Thanks for reporting.
