### ISSUE TITLE
Restart Codex Server (under tasks) doesn't seem to work.

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#361]
I am running codex 1.5.9 on a docker and when I click on "Restart Codex Server" under tasks nothing happens and I see the following in the log:

`2024-03-27 12:03:49 UTC WARNING Unknown admin library task_name: codex_restart`

Not urgent at all. Just something I noticed.

**Comment by ajslater** [comment]
Should be fixed in v1.5.10

**Comment by abillauer** [comment]
Confirmed fixed in 1.5.10. 
Thank you!
