### ISSUE TITLE
[Feature Suggestion] Show Breadcrumbs

### ISSUE THREAD

**Issue by beville** [ajslater/codex#371]
Often when using the web interface, I get a confused by what subset of books/folders I'm looking at. There's the combination of hierarchy position, filters, and search query that isn't always clear at a glance.   Sometimes there is a search query being applied but the search box is empty.  I think it's if I clear the search box before a search-in-progress finishes, and then the search is returned. 

I don't know if it would be too busy, but maybe that third-to-the top bar could show the current the hierarchy path, the filters, and current (if any) search query.   

Bonus if the path was click-to-jump and the filters were click-to-remove

**Comment by ajslater** [comment]
I agree it can be confusing and I like these suggestions. I’ll experiment a
bit with them. Thanks.

**Comment by ajslater** [comment]
This feature is included with [Codex v1.6.0](https://github.com/ajslater/codex/releases)
