### ISSUE TITLE
[Feature Request] Revert sorting after search is cleared

### ISSUE THREAD

**Issue by beville** [ajslater/codex#372]
Small but annoying thing:  If you do a search, the ordering automatically goes to "Search Score", which makes sense.  Once you clear the search string, the "Search Score" sorting remains, which has no meaning at that point.

I would be good if the ordering either reverted back to the prior setting, or went to a default, like "Name"

**Comment by ajslater** [comment]
Yeah this definitely needs to happen. Thanks.

**Comment by ajslater** [comment]
I think I've got this working for [v1.5.14](https://github.com/ajslater/codex/releases/tag/v1.5.14)
