### ISSUE TITLE
No comics found for these filters, no matter the filter

### ISSUE THREAD

**Issue by slarrain** [ajslater/codex#374]
I'm getting `No comics found for these filters` for any kind of filter.
In other words, I can't see a single comic. 
I've had Codex for years and it has been working properly. I'm not sure with which upgrade this started happening. But I'm currently on `codex v1.5.13a2` on a Synology NAS with Docker.
The strange thing is that on STATS, it shows almost 3.000 issues, which is correct.
The comic files are all there and I can see them with Mylar3 or browsing them.
Any clues?

**Comment by EldritchNuisance** [comment]
Check this bug out. Sounds like it is related to this issue
https://github.com/ajslater/codex/issues/344

**Comment by slarrain** [comment]
Thank you @EldritchNuisance for pointing this out. I ended up deleting all the configs folder and files and re running the docker and container and everything is back to normal.
