### ISSUE TITLE
Custom Covers documentation

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#394]
Hi,
I am sorry for the silly request. Is there documentation on how to set custom covers for  "Custom Covers for Folders, Publishers, Imprints, Series and Story Arcs."

Thanks!

**Comment by ajslater** [comment]
You should be able to find some hidden inside an expanding drawer on the
libraries page.

I’m mostly out of internet range this weekend.

**Comment by abillauer** [comment]
Thanks! Found it.
