### ISSUE TITLE
OPDS connection

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#399]
I am not sure if I am doing something wrong but I used to be able to connect via OPDS 1.2 on chunk on an ipad. It does not connect now. 

I enter the address and user/password and I get connection failed in chunky.
http://XXX.XXX.XXX.XXX:XXX/opds/v1.2/r/0/1

I have registration and non-users unchecked in flags.

If I navigate in an authenticated session to the OPDS address in my browser I get the expected XML.
If I navigate in a non-authenticated session to the OPDS address in my browser I get "403 Forbidden" which is probably expected behavior. 

Any help would be appreciated.

**Comment by ajslater** [comment]
I changed something for [v1.6.7](https://github.com/ajslater/codex/releases/tag/v1.6.7) that I think make chunky behave better.

v1.6.6 authorization seems to work with panels and other readers. Chunky behaves a bit strangely. I have Chunky for Mac desktop and it *sometimes* sends the entered username and password information in the headers to my test server and sometimes doesn't, and I'm not really sure why. I haven't spent the time to get consistent behavior out of it and figure it out, but I hope this change sorts you out.
