### ISSUE TITLE
User login issue

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#400]
I am seeing 2 odd behaviors from the system (codex v1.6.5 on docker).
 
1) when a create a new user and set the password and then try to login the password is invalid. The user sees the following:

![Screenshot 2024-07-09 at 7 19 26 PM](https://github.com/ajslater/codex/assets/73428493/5ca4f16c-d90e-4002-ad32-708263bec834)

As an admin if I change the password in the admin panel to the exact same password and then the user logs in it works. This seems to happen every time. 

2) When I create a user and they try to login I see the following:
![Screenshot 2024-07-09 at 7 19 38 PM](https://github.com/ajslater/codex/assets/73428493/4b03180c-9075-4d0f-9666-b0ca24a71853)

The users are not marked as staff. Registration and Non-User flags are unchecked.

**Comment by ajslater** [comment]
Issue number one was a doozy. That was flat broken. Thanks for reporting.
Issue number two was some bad UI  and would only show up (i think) if your user tried to access the admin panel.

Both should be fixed in [v1.6.6](https://github.com/ajslater/codex/releases/tag/v1.6.6)

**Comment by abillauer** [comment]
Confirmed. Both issues are fixed. Thanks so much!
