### ISSUE TITLE
Can't find link to admin panel

### ISSUE THREAD

**Issue by colinmanning1990** [ajslater/codex#412]
I feel like such an idiot, but I just cannot find the link to the admin panel in the browser menu. I've followed the instructions in the Administration document, I'm logged in as the admin, but the only options it shows me are to log out, change password, or poll libraries. Am I missing something really obvious? Apologies if so.

**Comment by abillauer** [comment]
Seeing the same thing. The admin panel option seems to have disappeared. codex v1.6.12

**Comment by ajslater** [comment]
This is quite a foolish bug and I'll fix it soon. But in the mean time you can get to the admin page with the url /admin/ after your codex url.

**Comment by ajslater** [comment]
Fixed in [v1.6.13](https://github.com/ajslater/codex/releases/tag/v1.6.13)
