### ISSUE TITLE
Clicking series link in comic tag doesn't work with "Top Group" as Issues or Folders

### ISSUE THREAD

**Issue by beville** [ajslater/codex#414]
I'm not quite sure what the proper behavior should be, so feel free to close this if I'm misunderstanding.

Here's the scenario:

I set the top group to "Folders" or "Issues".  I navigate a bit, find an interesting comic, and click on the tag icon to bring up the issue's metadata page.  If the Series name on that page is a link, I click on it, with the expectation that I will be sent to a page to see all the comics in that particular series. 

What happens is that the visible list doesn't seem to change.   If I started with "Folders" as the top, it _does_ change to series at the top, but the view still is the same folder.  If I start with "Issues" as the top, that doesn't change, and also the issues view stays the same.

**Comment by ajslater** [comment]
I can replicate. I'll look into this.

**Comment by ajslater** [comment]
Think I got this one fixed in [v1.6.14](https://github.com/ajslater/codex/releases/tag/v1.6.14). Thanks for reporting.

**Comment by beville** [comment]
That was quick!  

It does work now when starting from the topgroup:Folders, but still seems not to change anything when I start with topgroup:Issues. I tried clearing the cache, but same.

**Comment by ajslater** [comment]
I think I got it now [v1.6.15](https://github.com/ajslater/codex/releases/tag/v1.6.15)

**Comment by beville** [comment]
Yes, it works!  Very nice, thanks!
