### ISSUE TITLE
Position is not saved

### ISSUE THREAD

**Issue by hagelschaden** [ajslater/codex#424]
When I close a book on say page 10 and then close it I see a green line under the icon of the book indicating that the position has been saved. However, when I actually open it, it will alway open on the first page.

I'm using the docker version.

**Comment by abillauer** [comment]
I can confirm this happens in the web reader on my mac with codex v1.6.17 and Firefox 129.0.1 (64 Bit). 

OPDS (checked with panels) on an iPhone resumes where the reader left off.

**Comment by ajslater** [comment]
I have trouble reproducing this, but I have occasionally seen it, so I know it does happen.
Can people who are seeing this try logging out and then logging back in and tell me if the issue persists? I'm wondering if it's authentication related.

**Comment by abillauer** [comment]
Made no difference. I logged out and logged back in. Opened a book and progressed to page 9. Pressed escape and opened the book and it returned to the front cover.

**Comment by ermitovski** [comment]
Same for me, version v1.6.17 with Docker and using Safari.

**Comment by ajslater** [comment]
I think I've fixed in [v1.6.19](https://github.com/ajslater/codex/releases/tag/v1.6.19)

**Comment by abillauer** [comment]
I am still seeing the same behavior. I tested with both Safari and with Firefox. I am using codex v1.6.19 on docker.

**Comment by ajslater** [comment]
Changed some browser cache and bookmark behavior in [v1.7.0](https://github.com/ajslater/codex/releases/tag/v1.7.0) that hopefully addresses this.

**Comment by abillauer** [comment]
Tested and it works as expected on codex v1.7.0.

Thank you!
