### ISSUE TITLE
Story Arc Folder Structure

### ISSUE THREAD

**Issue by Earl0fPudding** [ajslater/codex#442]
Hi there, 

I haven't found any information on this sadly.
What is the current method of adding Story Arcs to a comic?
Do I have to add the comic like this?
/library/Comic_Name/Story_Arcs/Arc_Name1.pdf
/library/Comic_Name/Story_Arcs/Arc_Name2.pdf

I'm dealing with selfmade comics.

Thank you very much in advance!

Yours sincerely,
Martin

**Comment by ajslater** [comment]
Story Arc metadata is not extracted from folder structure but rather from comic metadata contained within comic archives.
CBZ & CBR comics are most often tagged with the [ComicInfo.xml](https://anansi-project.github.io/docs/comicinfo/schemas/v2.1) metadata format. Which is an xml file contained within the zip or rar file. ComicInfo.xml is also the only comic format that contains the StoryArc and StoryArcNumber tags which Codex uses to populate it's database.

Your example uses PDF files. There is no standard of comic metadata for PDFs. What little metadata there is in comic PDFs is often done in the style of prose books and is inconsistent and sparse. Codex does what it can to guess about this metadata. Sometimes Codex can figure out a publisher or series, but there's often more metadata to be gleaned from the filename. 

The tool that Codex uses to read metadata from comic archives and pdfs is called [Comicbox](https://github.com/ajslater/comicbox). I wrote this tool and It also writes comic metadata to comic archives and pdf files, but only from the command line. In this tool I've [included a hack](https://github.com/ajslater/comicbox?tab=readme-ov-file#writing-comicinfoxml-to-keywords) that writes the rich comic metadata format, ComicInfo.xml, into the keywords field of PDFs. This lets Comicbox and therefore Codex to read rich comic metadata from PDFs.

This is not a standard or used anywhere else. But it does exist for Codex so I though I'd mention it.
