### ISSUE TITLE
Tags View Redesign?

### ISSUE THREAD

**Issue by beville** [ajslater/codex#443]
This is a pretty subjective thing, not much of an issue as much as observations, but I think it might be worth revisiting the Tags display dialog. I feel like it's a bit too information sparse, and could probably be tightened up to provide more info at a glance.  Caveat that I'm not a design guy, so I'm just speaking from my gut rather than from any known design principles

Here's the Codex dialog for an issue with a long description:

![Screenshot 2024-11-01 at 22-37-04 Codex](https://github.com/user-attachments/assets/1331c730-f665-42be-bf58-1c1a87b6555a)

Some notes:
* All typeface is the same size
* Series name seems secondary to the publisher
* Technical data like timestamps, byte size, etc are shown before the more generally interesting "book-oriented" stuff like description and contributors.
* The layout generally is all stacked to the left, and leaves lot empty space to the right.  The label placement above the values tends make the whole layout be longer and need more scrolling to see everything.
* Pretty small thumbnail.

Compare this with the Komga version for the same comic (which it has as a stand-alone page for each book, but not a pop-up.  Is that a "landing page?") and I think it's a good example of how a re-work might be directed:
![Screenshot 2024-11-01 at 22-37-27 Komga - Watchmen (1986) - The Judge of All The Earth](https://github.com/user-attachments/assets/e6aad83d-31a0-40bd-a339-5caa89d2f3e0)

What I like about this layout:
* Larger fonts for the primary info
* Expandable description near the top
* Action buttons closer to the top

What I DON'T like about the Komga layout is that the issue story title is emphasized over the issue number there in a small stand-alone spot with no context. This probably makes more sense for Manga books, I guess?

My own preference would be for the first few line to be something like:

**Watchmen (1986) #3**
_"The Judge of All The Earth"_
DC Comics - 1 November 1986

with those first two lines being a larger size than the following ones.

I'm not sure how I feel about the placement of contributors vs summary, but I do think the other bonus tags of characters, locations, etc should come after.

Anyway, this is a pretty nit-picky stuff, but wanted to throw it out there for future consideration if you're ever thinking about tackling this.

**Comment by ajslater** [comment]
I've never been satisfied with the Tag screen layout and your suggestions and the reasons for them are helpful. Thanks. Keeping this open to remind me to address it.

**Comment by beville** [comment]
Thanks!  I may post other random screen shots here from other apps for reference as I come across them.

**Comment by ajslater** [comment]
I implemented some of your suggested changes. I should do more, but I released my progress so far with the v1.7.6 bugfix release.

**Comment by beville** [comment]
Oh, great!  That little re-arrangement seems way more useful at a glace already (to me anyway).

I have a few thoughts about the more aesthetic aspects, but I'll hold off until you tackle more.

Two more "functional" ideas that occur to me:

1. I always have the start year as the volume number, but if it's not, maybe the formatting for the volume info could be more explicit about it being a volume number with a prefix like `(vol. 2)` or just `v2`.  Maybe if the number is less than 1000 or something?  You might be doing like this already.
2. Maybe instead of alphabetic sorting for the contributors, use a traditional order for comic credits.  Along the lines of: creators, writers/plotters, artists/pencils/inks, colorists, letterers, editors, etc.  Though I wonder if there are complications to that that I'm not thinking of right now?

**Comment by ajslater** [comment]
1. This is supposed to already be happening as "vol. 1" but I just noticed a frontend crash i'll have to fix when there are no volumes. or no series. :(
2. I agree, a relevance order would be better.

Also, any aesthetic comments might help my direction here

**Comment by beville** [comment]
OK, just pure opinions here.  No offense taken if you ignore any or all of it.

![tag-notes](https://github.com/user-attachments/assets/f4e775c2-4050-4031-9a6a-6d8fee3c6673)
Referring to the red numbers:
1. Maybe drop the "box" shading for the first several lines, maybe including the page count and date.
2. Consider dynamically reducing the large font size when the window narrows, sort of like it already does with the cover thumbnail.
3. If there's no title text, that line seems still occupies vertical space.  Might as well collapse it.
4. Is the "Publisher" and "Imprint" header text needed?  Also, maybe just remove and collapse the line if neither are available.
5. Maybe concatenate the date text to a single string?
6. Is the "Contributors" header text needed?
7. Maybe treat this like a table with invisible lines, where the first column has the roles, and the second column has the names.  This would take less vertical space, and hopefully wouldn't be too cluttered.  This would allow a browser window to show a good chunk of the metadata without scrolling.
8. If you keep the box shading for these spots, maybe extend these to the right edge, to get rid of the ragged look.

Also also: for the the "tags" box with characters/teams/locations:  possibly follow the same table-like formatting as the contributors box idea in (7) above, just for consistency?

**Comment by beville** [comment]
Oh, maybe axe the self-obvious "Summary" header?

**Comment by beville** [comment]
Okay 1.7.8 looks great!  Just one last set of observations, I promise! 

Screen shot from a 10" iPad
![IMG_0502](https://github.com/user-attachments/assets/7661b3ba-8d6b-4b47-bae9-005dc7843904)

* Reduced font mode stuff:
   * The series and title lines are the same size (or maybe smaller than?) the other text. It would be nice to have those at least slightly larger than the other stuff, if only by a point size or two, just to assert their header nature.
   * The "Mark Read" and "Read" buttons are different height than the "Download" button
   * On my full-sized tablets, in portrait mode, the tags always show in the smaller size.  Maybe it's just my eyes getting older, but seems like the threshold was crossed too early.  In landscape mode, it looks great to me.

* "(Empty)" shows up if there is no imprint defined.

* Maybe there needs a slight bit more space below the cover thumbnail.  In some cases, it seems like the item below (either the download button or the series line, depending on the text and window size) will sometimes touch or overlap with the thumbnail.

* Does the identifiers box want the same table-like treatment as the other tag boxes?  

*  Just wanted to highlight the merging of the oval tags when there's multiple lines, like in the characters row above.  Seems legit as an active choice, but also might not have been one you were going for?

Thanks for tacking this stuff!  It think these changes so add some nice polish and really increase the at-a-glance usability.

**Comment by beville** [comment]
1.7.9: 
![](https://media1.tenor.com/m/LLLJYVQJNVAAAAAd/chefs-kiss-french-chef.gif)

**Comment by ajslater** [comment]
I think that's it for this round of tags view redesign. I'm gonna close this one out.
Thanks for all the help!
