### ISSUE TITLE
[Bug] Page counter overflow prevents book from opening.

### ISSUE THREAD

**Issue by Grandsome** [ajslater/codex#444]
I don't know how the database recorded a larger page count than the maximum but when it happens Codex can no longer render any page because of that error.
![image](https://github.com/user-attachments/assets/35348abd-396b-4caa-8026-e3703a432b79)

Nightly maintenance doesn't seem to be able to fix the error in the database.

**Comment by ajslater** [comment]
Wow. Thanks for reporting. I’ll take a look.

**Comment by ajslater** [comment]
I've found the source of the crash and will be releasing a fix for the crash part soon, but I'm not sure it will actually make your comic readable.
In the mean time if you update the mtime on that one comic and poll it will trigger a re-import of the comic and possibly fix the page count. e.g.
```sh
$ touch "Trilobite Ninjas #003.cbz"
```

**Comment by abillauer** [comment]
I changed the mtime on the comic and it didn't help. I still see the same error. 

I am not sure I understand how the reader would help. The error happens on poll and the comics don't appear in the library.

**Comment by ajslater** [comment]
I think this is fixed in [Codex v1.7.6](https://github.com/ajslater/codex/releases/tag/v1.7.6). Please reopen this bug if it still breaks.
