### ISSUE TITLE
[Feature Request] Configurable always-shown field in browser.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#446]
It appears that the always-shown field is the issue number.   The request would be to add a pulldown (or similar) to the side bar or top bar to choose what field is always shown.  This should at least include options to make the field show "Name" or "Filename".  Preferably it would include all the options in the "order by" pulldown.

Use Case:

It's specifically a problem in my case when I'm sorting by "Added Time" to see what's been most recently been added to my library and not every comic has a cover - since they're often coverless manga chapters.  Additionally, I do not import Metadata on Library Scan.   The issue number is only available to me once I've opened an issue.

**Comment by ajslater** [comment]
I added an always show filenames setting in the browser because it was really easy to do.
Your dropdown suggestion was a neat idea, but would require changing more code to get around some large query optimizations. And I think filename is the most likely use case.
