### ISSUE TITLE
Polling messages in the GUI

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#448]
When I poll all libraries the progress and steps no longer appear in the browser. There is no feedback that the library is being polled via the web UI. The panel reads "No librarian tasks running"

The libraries are polled and the logs confirm that. Just no GUI representation. I tried this in both firefox and safari on docker codex v1.7.6.

**Comment by ajslater** [comment]
Fixed in [v1.7.7](https://github.com/ajslater/codex/releases/tag/v1.7.7)

**Comment by abillauer** [comment]
I don't think this one is really fixed. If you poll all libraries a message pops up for a moment that it polled the first library and then the message disappears.

This is far from a major issue. The behavior is different than it was in previous versions.

I personally would love to see a entry in the log that says "XXXX Process started"  and a entry that says "XXXX Process completed in YYYY time." for each of the processes (Library poll, clean up, index rebuild, etc)

**Comment by ajslater** [comment]
> I don't think this one is really fixed. If you poll all libraries a message pops up for a moment that it polled the first library and then the message disappears.
> This is far from a major issue. The behavior is different than it was in previous versions. 

This is expected behavior if the poll takes a short amount of time and has no subsequent actions like importing comics.  And I think that's always been the behavior.

> I personally would love to see a entry in the log that says "XXXX Process started" and a entry that says "XXXX Process completed in YYYY time." for each of the processes (Library poll, clean up, index rebuild, etc)

That would be more informative, I think that might benefit from a separate admin tab that lists the jobs, the last time they ran and their run time in a filterable column sortable table.
