### ISSUE TITLE
v0.5.8 import errors and other tracebacks

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#47]
Attached is my full codex.log

/configs/codex/logs [hubcaps@moonbase] [10:53]
> grep Traceback codex.log | wc -l
249

[codex.log](https://github.com/ajslater/codex/files/5178452/codex.log)

**Comment by ajslater** [comment]
FIX PENDING
* Credit null name bug. https://github.com/ajslater/codex/issues/42
* 'NoneType' object has no attribute 'split' 
* 'decimal' referenced before assignment https://github.com/ajslater/codex/issues/40

FAIL BETTER:
* Failed to create cover: 
  - Bad magic number for file header
  - broken data stream when reading image file
  - Corrupt file - CRC check failed
We should now display a standard placeholder image for covers we 

UNSURE HOW TO FIX
* database is locked - with no other error clearly causing this
This is a bummer. Thinking on it.

WONT FIX ... YET
* Unsupported archive type
* Bad magic number for central directory
Should probably list these for the admin somewhere in the future.
