### ISSUE TITLE
Pagination introduces double scroll bars

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#49]
Not always, but in some cases that I'm not sure why, double scroll bars are happening when looking at issues with pagination now.

It isn't consistent, even in the same series. In Batman here for instance, the first page does it, the second and third don't, the fourth does, the fifth doesn't etc etc.

This can be quite annoying as you have to essentially "scroll to the bottom" twice, which from a user perspective causes quite a bit of frustration when attempting to progress through the pagination.

See attached gif for an example.

https://i.imgur.com/dSmbkkb.mp4

**Comment by ajslater** [comment]
Having trouble reproducing this one. Probably pretty easy to clean up once I can figure out how to make it happen.

**Comment by hubbcaps** [comment]
Taking a look at the pages it occurs on, I think the reason it's happening is the long comic title names, near the bottom row they're kinda so long they looks to be the reason for the tiny bit of second scroll bar.

**Comment by ajslater** [comment]
That makes sense. Was gonna check into fixing that next release anyway :)

**Comment by ajslater** [comment]
probably fixed. please re-open if not.
