### ISSUE TITLE
Reader - Height Mode Gap - Stacking Double Pages - None Functional Width Mode

### ISSUE THREAD

**Issue by hubbcaps** [ajslater/codex#52]
Sorry for combining three issues into one, but I figure they all come from the inital attempt for a fix for centering the comic page issue.

I've got an imgur album here showing the issues I'll describe

https://imgur.com/a/wcrgo2w

So first, in Height mode and by default there is a large blank gap at the bottom of each page, pretty ugly.

Second, when selecting Display two pages, it now stacks them with the Gap in between them, also pretty ugly.

Third, Width and Original seem to just place both pages into the same type of bounding box, perhaps a container you ended up centering for the fix for off center pages?

**Comment by hubbcaps** [comment]
Width mode still doesn't seem to stretch out to the full side of the screen

**Comment by ajslater** [comment]
This is why I named the UI setting "Shrink To" instead of "Fit To" or "Stretch To". I didn't want to stretch small images and introduce artifacts.

**Comment by hubbcaps** [comment]
Ahhhh that makes sense now that I actually open my eyes and read, and thinking on it is actually a bit more intuitive.
