### ISSUE TITLE
[Question] Library permissions

### ISSUE THREAD

**Issue by rg9400** [ajslater/codex#62]
I've been looking for a new comic server compared to Ubooquity, and someone recommended Codex. I spun up a quick test container, but I was curious if it had the ability to assign permissions like the below? I've been looking for something that can manage this since it's how I have Calibre-Web setup to great results.

1. By default, users do not need to sign in. This "guest" can view Library A, but not Library B or Library C.
2. Users can register, or have accounts created for them, or flow them from an upstream auth provider via something like auth-proxy. Either way, let's just assume that for now, they register manually. This new user can se see Library A and Library B automatically without me having to manually configure permissions.
3. Admins are the only ones that can see Library C (not shared with anyone else), unless they give a specific user access.

Essentially, can we modify permissions for guests (non-users), and can we assign new users to a default group with specific permissions. Can we those permissions be related to access of libraries? I did play around with the permissions a tiny bit, but they were complicated. Seems there is a lot of granular permissions, but I couldn't find specific access to Libraries. I also couldn't see how to manage Guest (not logged in) permissions, or how to assign new users a default set of permissions.

My goal is to basically restrict access to a specific Library to everyone but one or two people. I would want to do this without having to manage permissions for each new user if they register.

**Comment by ajslater** [comment]
This is a good idea. And not too difficult to implement.
But I wouldn't expect me to get to it until the first half of 2021. I'll update this ticket when it arrives.

**Comment by ajslater** [comment]
[Codex v0.9.1](https://github.com/ajslater/codex/releases/tag/v0.9.1) now supports private libraries.
See [the README for specifics](https://github.com/ajslater/codex#private-libraries).
