### ISSUE TITLE
Filename parser breaks on some comic names

### ISSUE THREAD

**Issue by ajslater** [ajslater/codex#77]
33475 OMAC v3 2.cbr
33465 Detective Comics 822.cbr
33469 Jonah Hex v2 10.cbr
33461 All-New Atom 2.cbr

throws a:
decimal.InvalidOperation

**Comment by jwm-evans** [comment]
I get the same error with my Heavy Metal issues. e.g.
```Heavy Metal 199905 (1999).cbz```

**Comment by dwightstanley** [comment]
I'm getting the [<class 'decimal.InvalidOperation'>] on these three:

/comics/Star Trek (1967)/Star Trek #11358 (1978).cbz

/comics/Dynabrite Comics (1978)/Dynabrite Comics #11358 - Star Trek - A Bomb In Time - The Psychocrystals (1978).cbz
-- | --

/comics/Supergirl (1996)/Supergirl 1000000 (1998) (digital) (OkC.O.M.P.U.T.O.-Novus).cbz

**Comment by ajslater** [comment]
Fixed [v0.6.8](https://github.com/ajslater/codex/releases/tag/v0.6.8)
