### ISSUE TITLE
Night of 1000 Wolves naming issue

### ISSUE THREAD

**Issue by Serneum** [ajslater/codex#78]
![image](https://user-images.githubusercontent.com/1091716/103393913-55af6b00-4af3-11eb-8510-5d5d0af22d81.png)

![image](https://user-images.githubusercontent.com/1091716/103393915-59db8880-4af3-11eb-8c34-81c8b9d0047f.png)

![image](https://user-images.githubusercontent.com/1091716/103393926-64961d80-4af3-11eb-91f4-af466e5c4bc7.png)

Mylar also suffered from [this issue](https://github.com/mylar3/mylar3/issues/275) as well. It could just be that it's tagged improperly, but I wanted to file this before tinkering with the files and changing anything.

**Comment by ajslater** [comment]
This may be partially a codex issue. In that in the absence of tags codex tries to extract metadata from the filename. While i will look into solving this particular case, solving for all possible filename schemas is very hard and maybe impossible. A number inside an alphanumeric phrase can probably be fixed.

But It is much more reliable to tag your comics.

**Comment by ajslater** [comment]
Fixed [v0.6.8](https://github.com/ajslater/codex/releases/tag/v0.6.8)
