### ISSUE TITLE
Codex splits volumes by imprint

### ISSUE THREAD

**Issue by Serneum** [ajslater/codex#82]
This may be intentional, but I've been fighting with some comics that have one or more issues tagged with an imprint being rendered as separate volumes. Ideally, they'd be grouped together as they are still the same series and the same volume. Or maybe a setting to allow this deviation in behavior.

I saw this with a single Captain Marvel issue (12, I think?) and I'm seeing it with Spawn 310-313. For the former, it was an issue in the middle of the series. For the latter, they are the newest issues so it's possible that Mylar will continue to tag new issues with the imprint and I'd rather not need to go retag each new issue

**Comment by ajslater** [comment]
The codex browser has a preference where you can disable or enable the browsing of Publishers, Imprints, Series or Volumes. If you don't want to give those comics all the same Imprint and Series you might try disabling one or both and I think it should group them in the same named Volume under Publisher.

**Comment by Serneum** [comment]
I'll double check, but the default seems to be Publisher. Even with that set, it was splitting on Imprints within the publisher

**Comment by Serneum** [comment]
Look like the default is Publisher and Volume
![image](https://user-images.githubusercontent.com/1091716/103449388-c4b4cd00-4c75-11eb-849a-71d33d4fce2c.png)

Spawn is split:
![image](https://user-images.githubusercontent.com/1091716/103449396-e31ac880-4c75-11eb-9ac2-9970a9e006d9.png)

One set has an Imprint:
![image](https://user-images.githubusercontent.com/1091716/103449401-f037b780-4c75-11eb-8e12-2b3254213b42.png)

The other doesn't:
![image](https://user-images.githubusercontent.com/1091716/103449405-fa59b600-4c75-11eb-8c7d-33770d4c5812.png)

**Comment by ajslater** [comment]
Oh good information. I see. Thank you. This is not the behavior I expected. I'll see if I can fix this.

**Comment by Serneum** [comment]
If it helps, I just did some more digging and it looks like this happens regardless of what you're viewing. Here it is even when only viewing Series:
![image](https://user-images.githubusercontent.com/1091716/103449434-4ad11380-4c76-11eb-9ef5-b344a4ac0fa2.png)

**Comment by ajslater** [comment]
The way the database works is that series with identical names under different imprints have different ids and are treated as different series. At this time I have no plans to change that and suggest changing the imprint metadata in your collection if you wish them to be in the same series.

I do understand that imprint metadata is often unevenly tagged in the wild and even from professional data sources and this constitutes something of a burden without an easy to use mass tagger.
