### ISSUE TITLE
Improperly detecting metadata for comic

### ISSUE THREAD

**Issue by Serneum** [ajslater/codex#83]
I found that one of my comics was being put into its own volume. It was detected as the 1975 Guardians of the Galaxy. I reran comictagger to be safe, verified the tag metadata, and then looked in Codex to see that the comic had not been moved. I've tried removing and re-adding the comic as well as tagging it again to no avail.

```
2020-12-31 17:08:07,141 librarian ThreadPoolExecutor-0_0 codex.librarian.importer INFO Created comic Guardians of the Galaxy: Marvel Presents #003
2020-12-31 17:08:07,178 ForkPoolWorker-1:5 ThreadPoolExecutor-0_0 codex.librarian.cover INFO Created cover thumbnail for: /comics/Guardians of the Galaxy (2019)/Guardians of the Galaxy 003 (2019).cbz
```
sudo comictagger -pt cr Guardians\ of\ the\ Galaxy\ 003\ \(2019\).cbz

--------- ComicRack tags ---------
series:     Guardians of the Galaxy
issue:      3
title:      The Final Gauntlet Three of Six
publisher:  Marvel
year:       2019
month:      05
day:        01
volume:     6
webLink:    https://comicvine.gamespot.com/guardians-of-the-galaxy-3-the-final-gauntlet-three/4000-703940/
storyArc:   The Final Gauntlet
characters: Annihilus, Beta Ray Bill, Black Dwarf, Black Swan, Corvus Glaive, Cosmic Ghost Rider, Ebony Maw, G-Type, Gamora, Gladiator, Groot, Hela, Moondragon, Nebula, Nova, Phyla-Vell, Proxima Midnight, Star-Lord, Starfox, Thanos, Wraith
teams:      Black Order, Dark Guardians , Guardians of the Galaxy
locations:  Space, The Negative Zone
comments:   The Dark Guardians ascend!

With a new Thanos rising, the galaxy calls for a group of heroes who will use any means necessary to end this threat.

Unfortunately for Star-Lord, that's NOT the Guardians of the Galaxy!

*List of covers and their creators:*
 Cover | Name                      | Creator(s)                 | Sidebar Location |
--------------------------------------------------------------------------------
 Reg   | Regular Cover             | David Marquez & Dean White | 1                |
 Var   | Marvel Meow Variant Cover | Nao Fuji                   | 2                |

notes:      Tagged with ComicTagger 1.3.0a0 using info from Comic Vine on 2020-12-31 12:03:24.  [Issue ID 703940]
credit:     Writer: Donny Cates
credit:     Penciller: Geoff Shaw
credit:     Inker: Geoff Shaw
credit:     Colorist: Marte Gracia
credit:     Letterer: Cory Petit
credit:     Cover: David Marquez
credit:     Cover: Dean White
credit:     Cover: Nao Fuji
credit:     Editor: Danny Khazem
credit:     Editor: Darren Shan
credit:     Editor: Jordan D. White
credit:     Editor: Lauren Amaro
```

**Comment by ajslater** [comment]
That log line from codex indicates that codex thinks the series name is "Guardians of the Galaxy: Marvel Presents" not "Guardians of the Galaxy" as per the tags from comictagger.

I wonder where it could be getting that series name. Your comictagger dump specifes ComicRack style comicinfo.xml tags. But wonder if codex could be picking up that name from a CBI or CoMet tags, or filename parsing. Codex is _supposed_ to give ComicRack tags precedence, but if you can verify what source the "Guardians of the Galaxy: Marvel Presents" series name is coming from it might indicate to me that codex has a precedence bug or something like that.

**Comment by Serneum** [comment]
CBL:
```
comictagger -pt cbl Guardians\ of\ the\ Galaxy\ 003\ \(2019\).cbz

------- ComicBookLover tags -------
series:    Guardians of the Galaxy
issue:     3
title:     The Final Gauntlet Three of Six
publisher: Marvel
year:      2019
month:     5
volume:    6
comments:  The Dark Guardians ascend!

With a new Thanos rising, the galaxy calls for a group of heroes who will use any means necessary to end this threat.

Unfortunately for Star-Lord, that's NOT the Guardians of the Galaxy!

*List of covers and their creators:*
 Cover | Name                      | Creator(s)                 | Sidebar Location |
--------------------------------------------------------------------------------
 Reg   | Regular Cover             | David Marquez & Dean White | 1                |
 Var   | Marvel Meow Variant Cover | Nao Fuji                   | 2                |

credit:    Other: Alan Fine
credit:    Other: C.B. Cebulski
credit:    Letterer: Cory Petit
credit:    Other: Dan Buckley
credit:    Editor: Danny Khazem
credit:    Assistant: Danny Khazem
credit:    Editor: Darren Shan
credit:    Cover: David Marquez
credit:    Cover: Dean White
credit:    Writer: Donny Cates
credit:    Artist: Geoff Shaw
credit:    Other: Joe Quesada
credit:    Editor: Jordan D. White
credit:    Other: Jordan D. White
credit:    Editor: Lauren Amaro
credit:    Assistant: Lauren Amaro
credit:    Colorist: Marte Gracia
credit:    Cover: Nao Fuji
```

CoMet came up empty

**Comment by ajslater** [comment]
Please reopen if this issue persists with Codex v0.7.0. The underlying comic metadata parsing library was updated and it may behave better now.
