### ISSUE TITLE
Docker image for armhf

### ISSUE THREAD

**Issue by bwrsandman** [ajslater/codex#84]
Would it be possible to publish an armhf version of the docker image on docker hub?

**Comment by ajslater** [comment]
The v0.6.8 version of codex, was built for docker [linux/armhf, which is a flavor of linux/arm/v7 i suppose](https://hub.docker.com/layers/ajslater/codex/0.6.8/images/sha256-a94ed14f4a340ea1d177ca11524e2cd51b9a2179c35a209afc4e27e09d7d2058?context=explore).

I have no way to test if it works on real hardware.
